Feat/safe transfer from
blockcoders/harmony-marketplace-sdk pull request #16
Opened 2022-01-26 22:36 UTC by bzuker

2022-01-27 12:37 UTC, AnnRiera submitted a review, later dismissed
LGTM!

2022-01-28 15:50 UTC, jarcodallo requested changes

2022-01-28 15:50 UTC, jarcodallo commented on src/hrc721.spec.ts
> +      expect(owner).to.be.oneOf([TEST_ACCOUNT_2.address, TEST_ACCOUNT_3.address])
put all the expects at the end.

2022-01-28 15:50 UTC, jarcodallo commented on src/hrc721.spec.ts
> +    }).timeout(30000)
this is not need it. Add a greater timeout in the mocha command like [this](https://github.com/blockcoders/near-rpc-providers/blob/main/package.json#L17-L18).

2022-01-28 15:50 UTC, jarcodallo commented on src/hrc721.spec.ts
> +    }).timeout(30000)
same

2022-01-31 20:11 UTC, jarcodallo approved these changes
LGTM

2022-01-31 20:11 UTC, merged